// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import CompetingUserSuccessChartController from "./competing_user_success_chart_controller"
application.register("competing-user-success-chart", CompetingUserSuccessChartController)

import DepartmentSuccessChartController from "./department_success_chart_controller"
application.register("department-success-chart", DepartmentSuccessChartController)

import HelloController from "./hello_controller"
application.register("hello", HelloController)

import PredictionsChartController from "./predictions_chart_controller"
application.register("predictions-chart", PredictionsChartController)

import SuccessChartController from "./success_chart_controller"
application.register("success-chart", SuccessChartController)
