# encoding: utf-8

CompetitionStructure.create([
  { description: "league" },
  { description: "tournament" },
  { description: "group and knockout stage"}])

Competition.create(name: "Mundial qatar 2022", competition_structure_id: 3, national_teams: true, groups: 8, teams_group: 4, rounds: 1,  begin: "2022-11-21T09:00:00+00:00", active: true)

Group.create([
  { competition_id: 1, name: "A", rounds: 1 },
  { competition_id: 1, name: "B", rounds: 1 },
  { competition_id: 1, name: "C", rounds: 1 },
  { competition_id: 1, name: "D", rounds: 1 },
  { competition_id: 1, name: "E", rounds: 1 },
  { competition_id: 1, name: "F", rounds: 1 },
  { competition_id: 1, name: "G", rounds: 1 },
  { competition_id: 1, name: "H", rounds: 1 }])

Team.create([{:national_team => true, :name =>"Afganistán", :iso_code => 4 , :iso_alpha3 =>"AFG", :iso_alpha2 =>"AF"},
    {:national_team => true, :name =>"Åland", :iso_code => 248 , :iso_alpha3 =>"ALA", :iso_alpha2 =>"AX"},
    {:national_team => true, :name =>"Albania", :iso_code => 8 , :iso_alpha3 =>"ALB", :iso_alpha2 =>"AL"},
    {:national_team => true, :name =>"Alemania", :iso_code => 276 , :iso_alpha3 =>"DEU", :iso_alpha2 =>"DE"},
    {:national_team => true, :name =>"Andorra", :iso_code => 20 , :iso_alpha3 =>"AND", :iso_alpha2 =>"AD"},
    {:national_team => true, :name =>"Angola", :iso_code => 24 , :iso_alpha3 =>"AGO", :iso_alpha2 =>"AO"},
    {:national_team => true, :name =>"Anguila", :iso_code => 660 , :iso_alpha3 =>"AIA", :iso_alpha2 =>"AI"},
    {:national_team => true, :name =>"Antigua y Barbuda", :iso_code => 28 , :iso_alpha3 =>"ATG", :iso_alpha2 =>"AG"},
    {:national_team => true, :name =>"Antillas Neerlandesas", :iso_code => 530 , :iso_alpha3 =>"ANT", :iso_alpha2 =>"AN"},
    {:national_team => true, :name =>"Arabia Saudita", :iso_code => 682 , :iso_alpha3 =>"SAU", :iso_alpha2 =>"SA"},
    {:national_team => true, :name =>"Argelia", :iso_code => 12 , :iso_alpha3 =>"DZA", :iso_alpha2 =>"DZ"},
    {:national_team => true, :name =>"Argentina", :iso_code => 32 , :iso_alpha3 =>"ARG", :iso_alpha2 =>"AR"},
    {:national_team => true, :name =>"Armenia", :iso_code => 51 , :iso_alpha3 =>"ARM", :iso_alpha2 =>"AM"},
    {:national_team => true, :name =>"Aruba", :iso_code => 533 , :iso_alpha3 =>"ABW", :iso_alpha2 =>"AW"},
    {:national_team => true, :name =>"Australia", :iso_code => 36 , :iso_alpha3 =>"AUS", :iso_alpha2 =>"AU"},
    {:national_team => true, :name =>"Austria", :iso_code => 40 , :iso_alpha3 =>"AUT", :iso_alpha2 =>"AT"},
    {:national_team => true, :name =>"Azerbaiyán", :iso_code => 31 , :iso_alpha3 =>"AZE", :iso_alpha2 =>"AZ"},
    {:national_team => true, :name =>"Bahamas", :iso_code => 44 , :iso_alpha3 =>"BHS", :iso_alpha2 =>"BS"},
    {:national_team => true, :name =>"Baréin", :iso_code => 48 , :iso_alpha3 =>"BHR", :iso_alpha2 =>"BH"},
    {:national_team => true, :name =>"Bangladés", :iso_code => 50 , :iso_alpha3 =>"BGD", :iso_alpha2 =>"BD"},
    {:national_team => true, :name =>"Barbados", :iso_code => 52 , :iso_alpha3 =>"BRB", :iso_alpha2 =>"BB"},
    {:national_team => true, :name =>"Bélgica", :iso_code => 56 , :iso_alpha3 =>"BEL", :iso_alpha2 =>"BE"},
    {:national_team => true, :name =>"Belice", :iso_code => 84 , :iso_alpha3 =>"BLZ", :iso_alpha2 =>"BZ"},
    {:national_team => true, :name =>"Benín", :iso_code => 204 , :iso_alpha3 =>"BEN", :iso_alpha2 =>"BJ"},
    {:national_team => true, :name =>"Bermudas", :iso_code => 60 , :iso_alpha3 =>"BMU", :iso_alpha2 =>"BM"},
    {:national_team => true, :name =>"Bielorrusia", :iso_code => 112 , :iso_alpha3 =>"BLR", :iso_alpha2 =>"BY"},
    {:national_team => true, :name =>"Birmania", :iso_code => 104 , :iso_alpha3 =>"MMR", :iso_alpha2 =>"MM"},
    {:national_team => true, :name =>"Bolivia", :iso_code => 68 , :iso_alpha3 =>"BOL", :iso_alpha2 =>"BO"},
    {:national_team => true, :name =>"Bosnia y Herzegovina", :iso_code => 70 , :iso_alpha3 =>"BIH", :iso_alpha2 =>"BA"},
    {:national_team => true, :name =>"Botsuana", :iso_code => 72 , :iso_alpha3 =>"BWA", :iso_alpha2 =>"BW"},
    {:national_team => true, :name =>"Isla Bouvet", :iso_code => 74 , :iso_alpha3 =>"BVT", :iso_alpha2 =>"BV"},
    {:national_team => true, :name =>"Brasil", :iso_code => 76 , :iso_alpha3 =>"BRA", :iso_alpha2 =>"BR"},
    {:national_team => true, :name =>"Brunéi", :iso_code => 96 , :iso_alpha3 =>"BRN", :iso_alpha2 =>"BN"},
    {:national_team => true, :name =>"Bulgaria", :iso_code => 100 , :iso_alpha3 =>"BGR", :iso_alpha2 =>"BG"},
    {:national_team => true, :name =>"Burkina Faso", :iso_code => 854 , :iso_alpha3 =>"BFA", :iso_alpha2 =>"BF"},
    {:national_team => true, :name =>"Burundi", :iso_code => 108 , :iso_alpha3 =>"BDI", :iso_alpha2 =>"BI"},
    {:national_team => true, :name =>"Bután", :iso_code => 64 , :iso_alpha3 =>"BTN", :iso_alpha2 =>"BT"},
    {:national_team => true, :name =>"Cabo Verde", :iso_code => 132 , :iso_alpha3 =>"CPV", :iso_alpha2 =>"CV"},
    {:national_team => true, :name =>"Islas Caimán", :iso_code => 136 , :iso_alpha3 =>"CYM", :iso_alpha2 =>"KY"},
    {:national_team => true, :name =>"Camboya", :iso_code => 116 , :iso_alpha3 =>"KHM", :iso_alpha2 =>"KH"},
    {:national_team => true, :name =>"Camerún", :iso_code => 120 , :iso_alpha3 =>"CMR", :iso_alpha2 =>"CM"},
    {:national_team => true, :name =>"Canadá", :iso_code => 124 , :iso_alpha3 =>"CAN", :iso_alpha2 =>"CA"},
    {:national_team => true, :name =>"República Centroafricana", :iso_code => 140 , :iso_alpha3 =>"CAF", :iso_alpha2 =>"CF"},
    {:national_team => true, :name =>"Chad", :iso_code => 148 , :iso_alpha3 =>"TCD", :iso_alpha2 =>"TD"},
    {:national_team => true, :name =>"República Checa", :iso_code => 203 , :iso_alpha3 =>"CZE", :iso_alpha2 =>"CZ"},
    {:national_team => true, :name =>"Chile", :iso_code => 152 , :iso_alpha3 =>"CHL", :iso_alpha2 =>"CL"},
    {:national_team => true, :name =>"China", :iso_code => 156 , :iso_alpha3 =>"CHN", :iso_alpha2 =>"CN"},
    {:national_team => true, :name =>"Chipre", :iso_code => 196 , :iso_alpha3 =>"CYP", :iso_alpha2 =>"CY"},
    {:national_team => true, :name =>"Islas Cocos", :iso_code => 166 , :iso_alpha3 =>"CCK", :iso_alpha2 =>"CC"},
    {:national_team => true, :name =>"Colombia", :iso_code => 170 , :iso_alpha3 =>"COL", :iso_alpha2 =>"CO"},
    {:national_team => true, :name =>"Comoras", :iso_code => 174 , :iso_alpha3 =>"COM", :iso_alpha2 =>"KM"},
    {:national_team => true, :name =>"República del Congo", :iso_code => 178 , :iso_alpha3 =>"COG", :iso_alpha2 =>"CG"},
    {:national_team => true, :name =>"Rep. Dem. del Congo", :iso_code => 180 , :iso_alpha3 =>"COD", :iso_alpha2 =>"CD"},
    {:national_team => true, :name =>"Islas Cook", :iso_code => 184 , :iso_alpha3 =>"COK", :iso_alpha2 =>"CK"},
    {:national_team => true, :name =>"Corea del Norte", :iso_code => 408 , :iso_alpha3 =>"PRK", :iso_alpha2 =>"KP"},
    {:national_team => true, :name =>"Corea del Sur", :iso_code => 410 , :iso_alpha3 =>"KOR", :iso_alpha2 =>"KR"},
    {:national_team => true, :name =>"Costa de Marfil", :iso_code => 384 , :iso_alpha3 =>"CIV", :iso_alpha2 =>"CI"},
    {:national_team => true, :name =>"Costa Rica", :iso_code => 188 , :iso_alpha3 =>"CRI", :iso_alpha2 =>"CR"},
    {:national_team => true, :name =>"Croacia", :iso_code => 191 , :iso_alpha3 =>"HRV", :iso_alpha2 =>"HR"},
    {:national_team => true, :name =>"Cuba", :iso_code => 192 , :iso_alpha3 =>"CUB", :iso_alpha2 =>"CU"},
    {:national_team => true, :name =>"Dinamarca", :iso_code => 208 , :iso_alpha3 =>"DNK", :iso_alpha2 =>"DK"},
    {:national_team => true, :name =>"Dominica", :iso_code => 212 , :iso_alpha3 =>"DMA", :iso_alpha2 =>"DM"},
    {:national_team => true, :name =>"República Dominicana", :iso_code => 214 , :iso_alpha3 =>"DOM", :iso_alpha2 =>"DO"},
    {:national_team => true, :name =>"Ecuador", :iso_code => 218 , :iso_alpha3 =>"ECU", :iso_alpha2 =>"EC"},
    {:national_team => true, :name =>"Egipto", :iso_code => 818 , :iso_alpha3 =>"EGY", :iso_alpha2 =>"EG"},
    {:national_team => true, :name =>"El Salvador", :iso_code => 222 , :iso_alpha3 =>"SLV", :iso_alpha2 =>"SV"},
    {:national_team => true, :name =>"Emiratos Árabes Unidos", :iso_code => 784 , :iso_alpha3 =>"ARE", :iso_alpha2 =>"AE"},
    {:national_team => true, :name =>"Eritrea", :iso_code => 232 , :iso_alpha3 =>"ERI", :iso_alpha2 =>"ER"},
    {:national_team => true, :name =>"Eslovaquia", :iso_code => 703 , :iso_alpha3 =>"SVK", :iso_alpha2 =>"SK"},
    {:national_team => true, :name =>"Eslovenia", :iso_code => 705 , :iso_alpha3 =>"SVN", :iso_alpha2 =>"SI"},
    {:national_team => true, :name =>"España* **", :iso_code => 724 , :iso_alpha3 =>"ESP", :iso_alpha2 =>"ES"},
    {:national_team => true, :name =>"Estados Unidos", :iso_code => 840 , :iso_alpha3 =>"USA", :iso_alpha2 =>"US"},
    {:national_team => true, :name =>"Estonia", :iso_code => 233 , :iso_alpha3 =>"EST", :iso_alpha2 =>"EE"},
    {:national_team => true, :name =>"Etiopía", :iso_code => 231 , :iso_alpha3 =>"ETH", :iso_alpha2 =>"ET"},
    {:national_team => true, :name =>"Islas Feroe", :iso_code => 234 , :iso_alpha3 =>"FRO", :iso_alpha2 =>"FO"},
    {:national_team => true, :name =>"Filipinas", :iso_code => 608 , :iso_alpha3 =>"PHL", :iso_alpha2 =>"PH"},
    {:national_team => true, :name =>"Finlandia", :iso_code => 246 , :iso_alpha3 =>"FIN", :iso_alpha2 =>"FI"},
    {:national_team => true, :name =>"Fiyi", :iso_code => 242 , :iso_alpha3 =>"FJI", :iso_alpha2 =>"FJ"},
    {:national_team => true, :name =>"Francia", :iso_code => 250 , :iso_alpha3 =>"FRA", :iso_alpha2 =>"FR"},
    {:national_team => true, :name =>"Gabón", :iso_code => 266 , :iso_alpha3 =>"GAB", :iso_alpha2 =>"GA"},
    {:national_team => true, :name =>"Gambia", :iso_code => 270 , :iso_alpha3 =>"GMB", :iso_alpha2 =>"GM"},
    {:national_team => true, :name =>"Georgia", :iso_code => 268 , :iso_alpha3 =>"GEO", :iso_alpha2 =>"GE"},
    {:national_team => true, :name =>"Islas Georgias del Sur y Sandwich del Sur", :iso_code => 239 , :iso_alpha3 =>"SGS", :iso_alpha2 =>"GS"},
    {:national_team => true, :name =>"Ghana", :iso_code => 288 , :iso_alpha3 =>"GHA", :iso_alpha2 =>"GH"},
    {:national_team => true, :name =>"Gibraltar", :iso_code => 292 , :iso_alpha3 =>"GIB", :iso_alpha2 =>"GI"},
    {:national_team => true, :name =>"Granada", :iso_code => 308 , :iso_alpha3 =>"GRD", :iso_alpha2 =>"GD"},
    {:national_team => true, :name =>"Grecia", :iso_code => 300 , :iso_alpha3 =>"GRC", :iso_alpha2 =>"GR"},
    {:national_team => true, :name =>"Groenlandia", :iso_code => 304 , :iso_alpha3 =>"GRL", :iso_alpha2 =>"GL"},
    {:national_team => true, :name =>"Guadalupe", :iso_code => 312 , :iso_alpha3 =>"GLP", :iso_alpha2 =>"GP"},
    {:national_team => true, :name =>"Guam", :iso_code => 316 , :iso_alpha3 =>"GUM", :iso_alpha2 =>"GU"},
    {:national_team => true, :name =>"Guatemala", :iso_code => 320 , :iso_alpha3 =>"GTM", :iso_alpha2 =>"GT"},
    {:national_team => true, :name =>"Guayana Francesa", :iso_code => 254 , :iso_alpha3 =>"GUF", :iso_alpha2 =>"GF"},
    {:national_team => true, :name =>"Guernsey", :iso_code => 831 , :iso_alpha3 =>"GGY", :iso_alpha2 =>"GG"},
    {:national_team => true, :name =>"Guinea", :iso_code => 324 , :iso_alpha3 =>"GIN", :iso_alpha2 =>"GN"},
    {:national_team => true, :name =>"Guinea Ecuatorial", :iso_code => 226 , :iso_alpha3 =>"GNQ", :iso_alpha2 =>"GQ"},
    {:national_team => true, :name =>"Guinea-Bisáu", :iso_code => 624 , :iso_alpha3 =>"GNB", :iso_alpha2 =>"GW"},
    {:national_team => true, :name =>"Guyana", :iso_code => 328 , :iso_alpha3 =>"GUY", :iso_alpha2 =>"GY"},
    {:national_team => true, :name =>"Haití", :iso_code => 332 , :iso_alpha3 =>"HTI", :iso_alpha2 =>"HT"},
    {:national_team => true, :name =>"Islas Heard y McDonald", :iso_code => 334 , :iso_alpha3 =>"HMD", :iso_alpha2 =>"HM"},
    {:national_team => true, :name =>"Honduras", :iso_code => 340 , :iso_alpha3 =>"HND", :iso_alpha2 =>"HN"},
    {:national_team => true, :name =>"Hong Kong", :iso_code => 344 , :iso_alpha3 =>"HKG", :iso_alpha2 =>"HK"},
    {:national_team => true, :name =>"Hungría", :iso_code => 348 , :iso_alpha3 =>"HUN", :iso_alpha2 =>"HU"},
    {:national_team => true, :name =>"India", :iso_code => 356 , :iso_alpha3 =>"IND", :iso_alpha2 =>"IN"},
    {:national_team => true, :name =>"Indonesia", :iso_code => 360 , :iso_alpha3 =>"IDN", :iso_alpha2 =>"ID"},
    {:national_team => true, :name =>"Irán", :iso_code => 364 , :iso_alpha3 =>"IRN", :iso_alpha2 =>"IR"},
    {:national_team => true, :name =>"Irak", :iso_code => 368 , :iso_alpha3 =>"IRQ", :iso_alpha2 =>"IQ"},
    {:national_team => true, :name =>"Irlanda", :iso_code => 372 , :iso_alpha3 =>"IRL", :iso_alpha2 =>"IE"},
    {:national_team => true, :name =>"Islandia", :iso_code => 352 , :iso_alpha3 =>"ISL", :iso_alpha2 =>"IS"},
    {:national_team => true, :name =>"Israel", :iso_code => 376 , :iso_alpha3 =>"ISR", :iso_alpha2 =>"IL"},
    {:national_team => true, :name =>"Italia", :iso_code => 380 , :iso_alpha3 =>"ITA", :iso_alpha2 =>"IT"},
    {:national_team => true, :name =>"Jamaica", :iso_code => 388 , :iso_alpha3 =>"JAM", :iso_alpha2 =>"JM"},
    {:national_team => true, :name =>"Japón", :iso_code => 392 , :iso_alpha3 =>"JPN", :iso_alpha2 =>"JP"},
    {:national_team => true, :name =>"Jersey", :iso_code => 832 , :iso_alpha3 =>"JEY", :iso_alpha2 =>"JE"},
    {:national_team => true, :name =>"Jordania", :iso_code => 400 , :iso_alpha3 =>"JOR", :iso_alpha2 =>"JO"},
    {:national_team => true, :name =>"Kazajistán", :iso_code => 398 , :iso_alpha3 =>"KAZ", :iso_alpha2 =>"KZ"},
    {:national_team => true, :name =>"Kenia", :iso_code => 404 , :iso_alpha3 =>"KEN", :iso_alpha2 =>"KE"},
    {:national_team => true, :name =>"Kirguistán", :iso_code => 417 , :iso_alpha3 =>"KGZ", :iso_alpha2 =>"KG"},
    {:national_team => true, :name =>"Kiribati", :iso_code => 296 , :iso_alpha3 =>"KIR", :iso_alpha2 =>"KI"},
    {:national_team => true, :name =>"Kuwait", :iso_code => 414 , :iso_alpha3 =>"KWT", :iso_alpha2 =>"KW"},
    {:national_team => true, :name =>"Laos", :iso_code => 418 , :iso_alpha3 =>"LAO", :iso_alpha2 =>"LA"},
    {:national_team => true, :name =>"Lesoto", :iso_code => 426 , :iso_alpha3 =>"LSO", :iso_alpha2 =>"LS"},
    {:national_team => true, :name =>"Letonia", :iso_code => 428 , :iso_alpha3 =>"LVA", :iso_alpha2 =>"LV"},
    {:national_team => true, :name =>"Líbano", :iso_code => 422 , :iso_alpha3 =>"LBN", :iso_alpha2 =>"LB"},
    {:national_team => true, :name =>"Liberia", :iso_code => 430 , :iso_alpha3 =>"LBR", :iso_alpha2 =>"LR"},
    {:national_team => true, :name =>"Libia", :iso_code => 434 , :iso_alpha3 =>"LBY", :iso_alpha2 =>"LY"},
    {:national_team => true, :name =>"Liechtenstein", :iso_code => 438 , :iso_alpha3 =>"LIE", :iso_alpha2 =>"LI"},
    {:national_team => true, :name =>"Lituania", :iso_code => 440 , :iso_alpha3 =>"LTU", :iso_alpha2 =>"LT"},
    {:national_team => true, :name =>"Luxemburgo", :iso_code => 442 , :iso_alpha3 =>"LUX", :iso_alpha2 =>"LU"},
    {:national_team => true, :name =>"Macao", :iso_code => 446 , :iso_alpha3 =>"MAC", :iso_alpha2 =>"MO"},
    {:national_team => true, :name =>"República de Macedonia", :iso_code => 807 , :iso_alpha3 =>"MKD", :iso_alpha2 =>"MK"},
    {:national_team => true, :name =>"Madagascar", :iso_code => 450 , :iso_alpha3 =>"MDG", :iso_alpha2 =>"MG"},
    {:national_team => true, :name =>"Malasia", :iso_code => 458 , :iso_alpha3 =>"MYS", :iso_alpha2 =>"MY"},
    {:national_team => true, :name =>"Malaui", :iso_code => 454 , :iso_alpha3 =>"MWI", :iso_alpha2 =>"MW"},
    {:national_team => true, :name =>"Maldivas", :iso_code => 462 , :iso_alpha3 =>"MDV", :iso_alpha2 =>"MV"},
    {:national_team => true, :name =>"Malí", :iso_code => 466 , :iso_alpha3 =>"MLI", :iso_alpha2 =>"ML"},
    {:national_team => true, :name =>"Malta", :iso_code => 470 , :iso_alpha3 =>"MLT", :iso_alpha2 =>"MT"},
    {:national_team => true, :name =>"Islas Malvinas", :iso_code => 238 , :iso_alpha3 =>"FLK", :iso_alpha2 =>"FK"},
    {:national_team => true, :name =>"Isla de Man", :iso_code => 833 , :iso_alpha3 =>"IMN", :iso_alpha2 =>"IM"},
    {:national_team => true, :name =>"Islas Marianas del Norte", :iso_code => 580 , :iso_alpha3 =>"MNP", :iso_alpha2 =>"MP"},
    {:national_team => true, :name =>"Marruecos", :iso_code => 504 , :iso_alpha3 =>"MAR", :iso_alpha2 =>"MA"},
    {:national_team => true, :name =>"Islas Marshall", :iso_code => 584 , :iso_alpha3 =>"MHL", :iso_alpha2 =>"MH"},
    {:national_team => true, :name =>"Martinica", :iso_code => 474 , :iso_alpha3 =>"MTQ", :iso_alpha2 =>"MQ"},
    {:national_team => true, :name =>"Mauricio", :iso_code => 480 , :iso_alpha3 =>"MUS", :iso_alpha2 =>"MU"},
    {:national_team => true, :name =>"Mauritania", :iso_code => 478 , :iso_alpha3 =>"MRT", :iso_alpha2 =>"MR"},
    {:national_team => true, :name =>"Mayotte", :iso_code => 175 , :iso_alpha3 =>"MYT", :iso_alpha2 =>"YT"},
    {:national_team => true, :name =>"México", :iso_code => 484 , :iso_alpha3 =>"MEX", :iso_alpha2 =>"MX"},
    {:national_team => true, :name =>"Micronesia", :iso_code => 583 , :iso_alpha3 =>"FSM", :iso_alpha2 =>"FM"},
    {:national_team => true, :name =>"Moldavia", :iso_code => 498 , :iso_alpha3 =>"MDA", :iso_alpha2 =>"MD"},
    {:national_team => true, :name =>"Mónaco", :iso_code => 492 , :iso_alpha3 =>"MCO", :iso_alpha2 =>"MC"},
    {:national_team => true, :name =>"Mongolia", :iso_code => 496 , :iso_alpha3 =>"MNG", :iso_alpha2 =>"MN"},
    {:national_team => true, :name =>"Montenegro", :iso_code => 499 , :iso_alpha3 =>"MNE", :iso_alpha2 =>"ME"},
    {:national_team => true, :name =>"Montserrat", :iso_code => 500 , :iso_alpha3 =>"MSR", :iso_alpha2 =>"MS"},
    {:national_team => true, :name =>"Mozambique", :iso_code => 508 , :iso_alpha3 =>"MOZ", :iso_alpha2 =>"MZ"},
    {:national_team => true, :name =>"Namibia", :iso_code => 516 , :iso_alpha3 =>"NAM", :iso_alpha2 =>"NA"},
    {:national_team => true, :name =>"Nauru", :iso_code => 520 , :iso_alpha3 =>"NRU", :iso_alpha2 =>"NR"},
    {:national_team => true, :name =>"Isla de Navidad", :iso_code => 162 , :iso_alpha3 =>"CXR", :iso_alpha2 =>"CX"},
    {:national_team => true, :name =>"Nepal", :iso_code => 524 , :iso_alpha3 =>"NPL", :iso_alpha2 =>"NP"},
    {:national_team => true, :name =>"Nicaragua", :iso_code => 558 , :iso_alpha3 =>"NIC", :iso_alpha2 =>"NI"},
    {:national_team => true, :name =>"Níger", :iso_code => 562 , :iso_alpha3 =>"NER", :iso_alpha2 =>"NE"},
    {:national_team => true, :name =>"Nigeria", :iso_code => 566 , :iso_alpha3 =>"NGA", :iso_alpha2 =>"NG"},
    {:national_team => true, :name =>"Niue", :iso_code => 570 , :iso_alpha3 =>"NIU", :iso_alpha2 =>"NU"},
    {:national_team => true, :name =>"Norfolk", :iso_code => 574 , :iso_alpha3 =>"NFK", :iso_alpha2 =>"NF"},
    {:national_team => true, :name =>"Noruega", :iso_code => 578 , :iso_alpha3 =>"NOR", :iso_alpha2 =>"NO"},
    {:national_team => true, :name =>"Nueva Caledonia", :iso_code => 540 , :iso_alpha3 =>"NCL", :iso_alpha2 =>"NC"},
    {:national_team => true, :name =>"Nueva Zelanda", :iso_code => 554 , :iso_alpha3 =>"NZL", :iso_alpha2 =>"NZ"},
    {:national_team => true, :name =>"Omán", :iso_code => 512 , :iso_alpha3 =>"OMN", :iso_alpha2 =>"OM"},
    {:national_team => true, :name =>"Países Bajos", :iso_code => 528 , :iso_alpha3 =>"NLD", :iso_alpha2 =>"NL"},
    {:national_team => true, :name =>"Pakistán", :iso_code => 586 , :iso_alpha3 =>"PAK", :iso_alpha2 =>"PK"},
    {:national_team => true, :name =>"Palaos", :iso_code => 585 , :iso_alpha3 =>"PLW", :iso_alpha2 =>"PW"},
    {:national_team => true, :name =>"Autoridad Nacional Palestina", :iso_code => 275 , :iso_alpha3 =>"PSE", :iso_alpha2 =>"PS"},
    {:national_team => true, :name =>"Panamá", :iso_code => 591 , :iso_alpha3 =>"PAN", :iso_alpha2 =>"PA"},
    {:national_team => true, :name =>"Papúa Nueva Guinea", :iso_code => 598 , :iso_alpha3 =>"PNG", :iso_alpha2 =>"PG"},
    {:national_team => true, :name =>"Paraguay", :iso_code => 600 , :iso_alpha3 =>"PRY", :iso_alpha2 =>"PY"},
    {:national_team => true, :name =>"Perú", :iso_code => 604 , :iso_alpha3 =>"PER", :iso_alpha2 =>"PE"},
    {:national_team => true, :name =>"Islas Pitcairn", :iso_code => 612 , :iso_alpha3 =>"PCN", :iso_alpha2 =>"PN"},
    {:national_team => true, :name =>"Polinesia Francesa", :iso_code => 258 , :iso_alpha3 =>"PYF", :iso_alpha2 =>"PF"},
    {:national_team => true, :name =>"Polonia", :iso_code => 616 , :iso_alpha3 =>"POL", :iso_alpha2 =>"PL"},
    {:national_team => true, :name =>"Portugal", :iso_code => 620 , :iso_alpha3 =>"PRT", :iso_alpha2 =>"PT"},
    {:national_team => true, :name =>"Puerto Rico", :iso_code => 630 , :iso_alpha3 =>"PRI", :iso_alpha2 =>"PR"},
    {:national_team => true, :name =>"Catar", :iso_code => 634 , :iso_alpha3 =>"QAT", :iso_alpha2 =>"QA"},
    {:national_team => true, :name =>"Inglaterra", :iso_code => 826 , :iso_alpha3 =>"GBR", :iso_alpha2 =>"GB"},
    {:national_team => true, :name =>"Reunión", :iso_code => 638 , :iso_alpha3 =>"REU", :iso_alpha2 =>"RE"},
    {:national_team => true, :name =>"Ruanda", :iso_code => 646 , :iso_alpha3 =>"RWA", :iso_alpha2 =>"RW"},
    {:national_team => true, :name =>"Rumania", :iso_code => 642 , :iso_alpha3 =>"ROU", :iso_alpha2 =>"RO"},
    {:national_team => true, :name =>"Rusia", :iso_code => 643 , :iso_alpha3 =>"RUS", :iso_alpha2 =>"RU"},
    {:national_team => true, :name =>"República Árabe Saharaui Democrática", :iso_code => 732 , :iso_alpha3 =>"ESH", :iso_alpha2 =>"EH"},
    {:national_team => true, :name =>"Islas Salomón", :iso_code => 90 , :iso_alpha3 =>"SLB", :iso_alpha2 =>"SB"},
    {:national_team => true, :name =>"Samoa", :iso_code => 882 , :iso_alpha3 =>"WSM", :iso_alpha2 =>"WS"},
    {:national_team => true, :name =>"Samoa Americana", :iso_code => 16 , :iso_alpha3 =>"ASM", :iso_alpha2 =>"AS"},
    {:national_team => true, :name =>"San Bartolomé", :iso_code => 652 , :iso_alpha3 =>"BLM", :iso_alpha2 =>"BL"},
    {:national_team => true, :name =>"San Cristóbal y Nieves", :iso_code => 659 , :iso_alpha3 =>"KNA", :iso_alpha2 =>"KN"},
    {:national_team => true, :name =>"San Marino", :iso_code => 674 , :iso_alpha3 =>"SMR", :iso_alpha2 =>"SM"},
    {:national_team => true, :name =>"San Martín", :iso_code => 663 , :iso_alpha3 =>"MAF", :iso_alpha2 =>"MF"},
    {:national_team => true, :name =>"San Pedro y Miquelón", :iso_code => 666 , :iso_alpha3 =>"SPM", :iso_alpha2 =>"PM"},
    {:national_team => true, :name =>"San Vicente y las Granadinas", :iso_code => 670 , :iso_alpha3 =>"VCT", :iso_alpha2 =>"VC"},
    {:national_team => true, :name =>"Santa Helena, A. y T.", :iso_code => 654 , :iso_alpha3 =>"SHN", :iso_alpha2 =>"SH"},
    {:national_team => true, :name =>"Santa Lucía", :iso_code => 662 , :iso_alpha3 =>"LCA", :iso_alpha2 =>"LC"},
    {:national_team => true, :name =>"Santo Tomé y Príncipe", :iso_code => 678 , :iso_alpha3 =>"STP", :iso_alpha2 =>"ST"},
    {:national_team => true, :name =>"Senegal", :iso_code => 686 , :iso_alpha3 =>"SEN", :iso_alpha2 =>"SN"},
    {:national_team => true, :name =>"Serbia", :iso_code => 688 , :iso_alpha3 =>"SRB", :iso_alpha2 =>"RS"},
    {:national_team => true, :name =>"Seychelles", :iso_code => 690 , :iso_alpha3 =>"SYC", :iso_alpha2 =>"SC"},
    {:national_team => true, :name =>"Sierra Leona", :iso_code => 694 , :iso_alpha3 =>"SLE", :iso_alpha2 =>"SL"},
    {:national_team => true, :name =>"Singapur", :iso_code => 702 , :iso_alpha3 =>"SGP", :iso_alpha2 =>"SG"},
    {:national_team => true, :name =>"Siria", :iso_code => 760 , :iso_alpha3 =>"SYR", :iso_alpha2 =>"SY"},
    {:national_team => true, :name =>"Somalia", :iso_code => 706 , :iso_alpha3 =>"SOM", :iso_alpha2 =>"SO"},
    {:national_team => true, :name =>"Sri Lanka", :iso_code => 144 , :iso_alpha3 =>"LKA", :iso_alpha2 =>"LK"},
    {:national_team => true, :name =>"Suazilandia", :iso_code => 748 , :iso_alpha3 =>"SWZ", :iso_alpha2 =>"SZ"},
    {:national_team => true, :name =>"Sudáfrica", :iso_code => 710 , :iso_alpha3 =>"ZAF", :iso_alpha2 =>"ZA"},
    {:national_team => true, :name =>"Sudán", :iso_code => 729 , :iso_alpha3 =>"SDN", :iso_alpha2 =>"SD"},
    {:national_team => true, :name =>"Sudán del Sur", :iso_code => 728 , :iso_alpha3 =>"SSD", :iso_alpha2 =>"SS"},
    {:national_team => true, :name =>"Suecia", :iso_code => 752 , :iso_alpha3 =>"SWE", :iso_alpha2 =>"SE"},
    {:national_team => true, :name =>"Suiza", :iso_code => 756 , :iso_alpha3 =>"CHE", :iso_alpha2 =>"CH"},
    {:national_team => true, :name =>"Surinam", :iso_code => 740 , :iso_alpha3 =>"SUR", :iso_alpha2 =>"SR"},
    {:national_team => true, :name =>"Svalbard y Jan Mayen", :iso_code => 744 , :iso_alpha3 =>"SJM", :iso_alpha2 =>"SJ"},
    {:national_team => true, :name =>"Tailandia", :iso_code => 764 , :iso_alpha3 =>"THA", :iso_alpha2 =>"TH"},
    {:national_team => true, :name =>"Taiwán", :iso_code => 158 , :iso_alpha3 =>"TWN", :iso_alpha2 =>"TW"},
    {:national_team => true, :name =>"Tanzania", :iso_code => 834 , :iso_alpha3 =>"TZA", :iso_alpha2 =>"TZ"},
    {:national_team => true, :name =>"Tayikistán", :iso_code => 762 , :iso_alpha3 =>"TJK", :iso_alpha2 =>"TJ"},
    {:national_team => true, :name =>"Territorio Británico del Océano Índico", :iso_code => 86 , :iso_alpha3 =>"IOT", :iso_alpha2 =>"IO"},
    {:national_team => true, :name =>"Territorios Australes Franceses", :iso_code => 260 , :iso_alpha3 =>"ATF", :iso_alpha2 =>"TF"},
    {:national_team => true, :name =>"Timor Oriental", :iso_code => 626 , :iso_alpha3 =>"TLS", :iso_alpha2 =>"TL"},
    {:national_team => true, :name =>"Togo", :iso_code => 768 , :iso_alpha3 =>"TGO", :iso_alpha2 =>"TG"},
    {:national_team => true, :name =>"Tokelau", :iso_code => 772 , :iso_alpha3 =>"TKL", :iso_alpha2 =>"TK"},
    {:national_team => true, :name =>"Tonga", :iso_code => 776 , :iso_alpha3 =>"TON", :iso_alpha2 =>"TO"},
    {:national_team => true, :name =>"Trinidad y Tobago", :iso_code => 780 , :iso_alpha3 =>"TTO", :iso_alpha2 =>"TT"},
    {:national_team => true, :name =>"Túnez", :iso_code => 788 , :iso_alpha3 =>"TUN", :iso_alpha2 =>"TN"},
    {:national_team => true, :name =>"Islas Turcas y Caicos", :iso_code => 796 , :iso_alpha3 =>"TCA", :iso_alpha2 =>"TC"},
    {:national_team => true, :name =>"Turkmenistán", :iso_code => 795 , :iso_alpha3 =>"TKM", :iso_alpha2 =>"TM"},
    {:national_team => true, :name =>"Turquía", :iso_code => 792 , :iso_alpha3 =>"TUR", :iso_alpha2 =>"TR"},
    {:national_team => true, :name =>"Tuvalu", :iso_code => 798 , :iso_alpha3 =>"TUV", :iso_alpha2 =>"TV"},
    {:national_team => true, :name =>"Ucrania", :iso_code => 804 , :iso_alpha3 =>"UKR", :iso_alpha2 =>"UA"},
    {:national_team => true, :name =>"Uganda", :iso_code => 800 , :iso_alpha3 =>"UGA", :iso_alpha2 =>"UG"},
    {:national_team => true, :name =>"Uruguay", :iso_code => 858 , :iso_alpha3 =>"URY", :iso_alpha2 =>"UY"},
    {:national_team => true, :name =>"Uzbekistán", :iso_code => 860 , :iso_alpha3 =>"UZB", :iso_alpha2 =>"UZ"},
    {:national_team => true, :name =>"Vanuatu", :iso_code => 548 , :iso_alpha3 =>"VUT", :iso_alpha2 =>"VU"},
    {:national_team => true, :name =>"Ciudad del Vaticano", :iso_code => 336 , :iso_alpha3 =>"VAT", :iso_alpha2 =>"VA"},
    {:national_team => true, :name =>"Venezuela", :iso_code => 862 , :iso_alpha3 =>"VEN", :iso_alpha2 =>"VE"},
    {:national_team => true, :name =>"Vietnam", :iso_code => 704 , :iso_alpha3 =>"VNM", :iso_alpha2 =>"VN"},
    {:national_team => true, :name =>"Islas Vírgenes Británicas", :iso_code => 92 , :iso_alpha3 =>"VGB", :iso_alpha2 =>"VG"},
    {:national_team => true, :name =>"Islas Vírgenes de los Estados Unidos", :iso_code => 850 , :iso_alpha3 =>"VIR", :iso_alpha2 =>"VI"},
    {:national_team => true, :name =>"Wallis y Futuna", :iso_code => 876 , :iso_alpha3 =>"WLF", :iso_alpha2 =>"WF"},
    {:national_team => true, :name =>"Yemen", :iso_code => 887 , :iso_alpha3 =>"YEM", :iso_alpha2 =>"YE"},
    {:national_team => true, :name =>"Yibuti", :iso_code => 262 , :iso_alpha3 =>"DJI", :iso_alpha2 =>"DJ"},
    {:national_team => true, :name =>"Zambia", :iso_code => 894 , :iso_alpha3 =>"ZMB", :iso_alpha2 =>"ZM"},
    {:national_team => true, :name =>"Zimbabue", :iso_code => 716 , :iso_alpha3 =>"ZWE", :iso_alpha2 =>"ZW"},
    {:national_team => true, :name => "Gales", :iso_code => 1826, :iso_alpha3 => "GB-WLS", :iso_alpha2 => "GB-WLS" }])

CompetingTeam.create([
  { group_id: 1, team_id: 180 },
  { group_id: 1, team_id: 64 },
  { group_id: 1, team_id: 199 },
  { group_id: 1, team_id: 167 },
  { group_id: 2, team_id: 181 },
  { group_id: 2, team_id: 105 },
  { group_id: 2, team_id: 72 },
  { group_id: 2, team_id: 248 },
  { group_id: 3, team_id: 12 },
  { group_id: 3, team_id: 10 },
  { group_id: 3, team_id: 146 },
  { group_id: 3, team_id: 177 },
  { group_id: 4, team_id: 79 },
  { group_id: 4, team_id: 15 },
  { group_id: 4, team_id: 61 },
  { group_id: 4, team_id: 226 },
  { group_id: 5, team_id: 71 },
  { group_id: 5, team_id: 58 },
  { group_id: 5, team_id: 4 },
  { group_id: 5, team_id: 112 },
  { group_id: 6, team_id: 22 },
  { group_id: 6, team_id: 42 },
  { group_id: 6, team_id: 140 },
  { group_id: 6, team_id: 59 },
  { group_id: 7, team_id: 32 },
  { group_id: 7, team_id: 200 },
  { group_id: 7, team_id: 212 },
  { group_id: 7, team_id: 41 },
  { group_id: 8, team_id: 178 },
  { group_id: 8, team_id: 84 },
  { group_id: 8, team_id: 233 },
  { group_id: 8, team_id: 56 }
])

competing_teams = CompetingTeam.all

competing_teams.each do |ct|
  CompetingTeamScore.create( competing_team_id: ct.id )
end

Country.create([{:name =>"Afganistán", :iso_code => 4 , :iso_alpha3 =>"AFG", :iso_alpha2 =>"AF"},
  {:name =>"Åland", :iso_code => 248 , :iso_alpha3 =>"ALA", :iso_alpha2 =>"AX"},
  {:name =>"Albania", :iso_code => 8 , :iso_alpha3 =>"ALB", :iso_alpha2 =>"AL"},
  {:name =>"Alemania", :iso_code => 276 , :iso_alpha3 =>"DEU", :iso_alpha2 =>"DE"},
  {:name =>"Andorra", :iso_code => 20 , :iso_alpha3 =>"AND", :iso_alpha2 =>"AD"},
  {:name =>"Angola", :iso_code => 24 , :iso_alpha3 =>"AGO", :iso_alpha2 =>"AO"},
  {:name =>"Anguila", :iso_code => 660 , :iso_alpha3 =>"AIA", :iso_alpha2 =>"AI"},
  {:name =>"Antigua y Barbuda", :iso_code => 28 , :iso_alpha3 =>"ATG", :iso_alpha2 =>"AG"},
  {:name =>"Antillas Neerlandesas", :iso_code => 530 , :iso_alpha3 =>"ANT", :iso_alpha2 =>"AN"},
  {:name =>"Arabia Saudita", :iso_code => 682 , :iso_alpha3 =>"SAU", :iso_alpha2 =>"SA"},
  {:name =>"Argelia", :iso_code => 12 , :iso_alpha3 =>"DZA", :iso_alpha2 =>"DZ"},
  {:name =>"Argentina", :iso_code => 32 , :iso_alpha3 =>"ARG", :iso_alpha2 =>"AR"},
  {:name =>"Armenia", :iso_code => 51 , :iso_alpha3 =>"ARM", :iso_alpha2 =>"AM"},
  {:name =>"Aruba", :iso_code => 533 , :iso_alpha3 =>"ABW", :iso_alpha2 =>"AW"},
  {:name =>"Australia", :iso_code => 36 , :iso_alpha3 =>"AUS", :iso_alpha2 =>"AU"},
  {:name =>"Austria", :iso_code => 40 , :iso_alpha3 =>"AUT", :iso_alpha2 =>"AT"},
  {:name =>"Azerbaiyán", :iso_code => 31 , :iso_alpha3 =>"AZE", :iso_alpha2 =>"AZ"},
  {:name =>"Bahamas", :iso_code => 44 , :iso_alpha3 =>"BHS", :iso_alpha2 =>"BS"},
  {:name =>"Baréin", :iso_code => 48 , :iso_alpha3 =>"BHR", :iso_alpha2 =>"BH"},
  {:name =>"Bangladés", :iso_code => 50 , :iso_alpha3 =>"BGD", :iso_alpha2 =>"BD"},
  {:name =>"Barbados", :iso_code => 52 , :iso_alpha3 =>"BRB", :iso_alpha2 =>"BB"},
  {:name =>"Bélgica", :iso_code => 56 , :iso_alpha3 =>"BEL", :iso_alpha2 =>"BE"},
  {:name =>"Belice", :iso_code => 84 , :iso_alpha3 =>"BLZ", :iso_alpha2 =>"BZ"},
  {:name =>"Benín", :iso_code => 204 , :iso_alpha3 =>"BEN", :iso_alpha2 =>"BJ"},
  {:name =>"Bermudas", :iso_code => 60 , :iso_alpha3 =>"BMU", :iso_alpha2 =>"BM"},
  {:name =>"Bielorrusia", :iso_code => 112 , :iso_alpha3 =>"BLR", :iso_alpha2 =>"BY"},
  {:name =>"Birmania", :iso_code => 104 , :iso_alpha3 =>"MMR", :iso_alpha2 =>"MM"},
  {:name =>"Bolivia", :iso_code => 68 , :iso_alpha3 =>"BOL", :iso_alpha2 =>"BO"},
  {:name =>"Bosnia y Herzegovina", :iso_code => 70 , :iso_alpha3 =>"BIH", :iso_alpha2 =>"BA"},
  {:name =>"Botsuana", :iso_code => 72 , :iso_alpha3 =>"BWA", :iso_alpha2 =>"BW"},
  {:name =>"Isla Bouvet", :iso_code => 74 , :iso_alpha3 =>"BVT", :iso_alpha2 =>"BV"},
  {:name =>"Brasil", :iso_code => 76 , :iso_alpha3 =>"BRA", :iso_alpha2 =>"BR"},
  {:name =>"Brunéi", :iso_code => 96 , :iso_alpha3 =>"BRN", :iso_alpha2 =>"BN"},
  {:name =>"Bulgaria", :iso_code => 100 , :iso_alpha3 =>"BGR", :iso_alpha2 =>"BG"},
  {:name =>"Burkina Faso", :iso_code => 854 , :iso_alpha3 =>"BFA", :iso_alpha2 =>"BF"},
  {:name =>"Burundi", :iso_code => 108 , :iso_alpha3 =>"BDI", :iso_alpha2 =>"BI"},
  {:name =>"Bután", :iso_code => 64 , :iso_alpha3 =>"BTN", :iso_alpha2 =>"BT"},
  {:name =>"Cabo Verde", :iso_code => 132 , :iso_alpha3 =>"CPV", :iso_alpha2 =>"CV"},
  {:name =>"Islas Caimán", :iso_code => 136 , :iso_alpha3 =>"CYM", :iso_alpha2 =>"KY"},
  {:name =>"Camboya", :iso_code => 116 , :iso_alpha3 =>"KHM", :iso_alpha2 =>"KH"},
  {:name =>"Camerún", :iso_code => 120 , :iso_alpha3 =>"CMR", :iso_alpha2 =>"CM"},
  {:name =>"Canadá", :iso_code => 124 , :iso_alpha3 =>"CAN", :iso_alpha2 =>"CA"},
  {:name =>"República Centroafricana", :iso_code => 140 , :iso_alpha3 =>"CAF", :iso_alpha2 =>"CF"},
  {:name =>"Chad", :iso_code => 148 , :iso_alpha3 =>"TCD", :iso_alpha2 =>"TD"},
  {:name =>"República Checa", :iso_code => 203 , :iso_alpha3 =>"CZE", :iso_alpha2 =>"CZ"},
  {:name =>"Chile", :iso_code => 152 , :iso_alpha3 =>"CHL", :iso_alpha2 =>"CL"},
  {:name =>"China", :iso_code => 156 , :iso_alpha3 =>"CHN", :iso_alpha2 =>"CN"},
  {:name =>"Chipre", :iso_code => 196 , :iso_alpha3 =>"CYP", :iso_alpha2 =>"CY"},
  {:name =>"Islas Cocos", :iso_code => 166 , :iso_alpha3 =>"CCK", :iso_alpha2 =>"CC"},
  {:name =>"Colombia", :iso_code => 170 , :iso_alpha3 =>"COL", :iso_alpha2 =>"CO"},
  {:name =>"Comoras", :iso_code => 174 , :iso_alpha3 =>"COM", :iso_alpha2 =>"KM"},
  {:name =>"República del Congo", :iso_code => 178 , :iso_alpha3 =>"COG", :iso_alpha2 =>"CG"},
  {:name =>"Rep. Dem. del Congo", :iso_code => 180 , :iso_alpha3 =>"COD", :iso_alpha2 =>"CD"},
  {:name =>"Islas Cook", :iso_code => 184 , :iso_alpha3 =>"COK", :iso_alpha2 =>"CK"},
  {:name =>"Corea del Norte", :iso_code => 408 , :iso_alpha3 =>"PRK", :iso_alpha2 =>"KP"},
  {:name =>"Corea del Sur", :iso_code => 410 , :iso_alpha3 =>"KOR", :iso_alpha2 =>"KR"},
  {:name =>"Costa de Marfil", :iso_code => 384 , :iso_alpha3 =>"CIV", :iso_alpha2 =>"CI"},
  {:name =>"Costa Rica", :iso_code => 188 , :iso_alpha3 =>"CRI", :iso_alpha2 =>"CR"},
  {:name =>"Croacia", :iso_code => 191 , :iso_alpha3 =>"HRV", :iso_alpha2 =>"HR"},
  {:name =>"Cuba", :iso_code => 192 , :iso_alpha3 =>"CUB", :iso_alpha2 =>"CU"},
  {:name =>"Dinamarca", :iso_code => 208 , :iso_alpha3 =>"DNK", :iso_alpha2 =>"DK"},
  {:name =>"Dominica", :iso_code => 212 , :iso_alpha3 =>"DMA", :iso_alpha2 =>"DM"},
  {:name =>"República Dominicana", :iso_code => 214 , :iso_alpha3 =>"DOM", :iso_alpha2 =>"DO"},
  {:name =>"Ecuador", :iso_code => 218 , :iso_alpha3 =>"ECU", :iso_alpha2 =>"EC"},
  {:name =>"Egipto", :iso_code => 818 , :iso_alpha3 =>"EGY", :iso_alpha2 =>"EG"},
  {:name =>"El Salvador", :iso_code => 222 , :iso_alpha3 =>"SLV", :iso_alpha2 =>"SV"},
  {:name =>"Emiratos Árabes Unidos", :iso_code => 784 , :iso_alpha3 =>"ARE", :iso_alpha2 =>"AE"},
  {:name =>"Eritrea", :iso_code => 232 , :iso_alpha3 =>"ERI", :iso_alpha2 =>"ER"},
  {:name =>"Eslovaquia", :iso_code => 703 , :iso_alpha3 =>"SVK", :iso_alpha2 =>"SK"},
  {:name =>"Eslovenia", :iso_code => 705 , :iso_alpha3 =>"SVN", :iso_alpha2 =>"SI"},
  {:name =>"España* **", :iso_code => 724 , :iso_alpha3 =>"ESP", :iso_alpha2 =>"ES"},
  {:name =>"Estados Unidos", :iso_code => 840 , :iso_alpha3 =>"USA", :iso_alpha2 =>"US"},
  {:name =>"Estonia", :iso_code => 233 , :iso_alpha3 =>"EST", :iso_alpha2 =>"EE"},
  {:name =>"Etiopía", :iso_code => 231 , :iso_alpha3 =>"ETH", :iso_alpha2 =>"ET"},
  {:name =>"Islas Feroe", :iso_code => 234 , :iso_alpha3 =>"FRO", :iso_alpha2 =>"FO"},
  {:name =>"Filipinas", :iso_code => 608 , :iso_alpha3 =>"PHL", :iso_alpha2 =>"PH"},
  {:name =>"Finlandia", :iso_code => 246 , :iso_alpha3 =>"FIN", :iso_alpha2 =>"FI"},
  {:name =>"Fiyi", :iso_code => 242 , :iso_alpha3 =>"FJI", :iso_alpha2 =>"FJ"},
  {:name =>"Francia", :iso_code => 250 , :iso_alpha3 =>"FRA", :iso_alpha2 =>"FR"},
  {:name =>"Gabón", :iso_code => 266 , :iso_alpha3 =>"GAB", :iso_alpha2 =>"GA"},
  {:name =>"Gambia", :iso_code => 270 , :iso_alpha3 =>"GMB", :iso_alpha2 =>"GM"},
  {:name =>"Georgia", :iso_code => 268 , :iso_alpha3 =>"GEO", :iso_alpha2 =>"GE"},
  {:name =>"Islas Georgias del Sur y Sandwich del Sur", :iso_code => 239 , :iso_alpha3 =>"SGS", :iso_alpha2 =>"GS"},
  {:name =>"Ghana", :iso_code => 288 , :iso_alpha3 =>"GHA", :iso_alpha2 =>"GH"},
  {:name =>"Gibraltar", :iso_code => 292 , :iso_alpha3 =>"GIB", :iso_alpha2 =>"GI"},
  {:name =>"Granada", :iso_code => 308 , :iso_alpha3 =>"GRD", :iso_alpha2 =>"GD"},
  {:name =>"Grecia", :iso_code => 300 , :iso_alpha3 =>"GRC", :iso_alpha2 =>"GR"},
  {:name =>"Groenlandia", :iso_code => 304 , :iso_alpha3 =>"GRL", :iso_alpha2 =>"GL"},
  {:name =>"Guadalupe", :iso_code => 312 , :iso_alpha3 =>"GLP", :iso_alpha2 =>"GP"},
  {:name =>"Guam", :iso_code => 316 , :iso_alpha3 =>"GUM", :iso_alpha2 =>"GU"},
  {:name =>"Guatemala", :iso_code => 320 , :iso_alpha3 =>"GTM", :iso_alpha2 =>"GT"},
  {:name =>"Guayana Francesa", :iso_code => 254 , :iso_alpha3 =>"GUF", :iso_alpha2 =>"GF"},
  {:name =>"Guernsey", :iso_code => 831 , :iso_alpha3 =>"GGY", :iso_alpha2 =>"GG"},
  {:name =>"Guinea", :iso_code => 324 , :iso_alpha3 =>"GIN", :iso_alpha2 =>"GN"},
  {:name =>"Guinea Ecuatorial", :iso_code => 226 , :iso_alpha3 =>"GNQ", :iso_alpha2 =>"GQ"},
  {:name =>"Guinea-Bisáu", :iso_code => 624 , :iso_alpha3 =>"GNB", :iso_alpha2 =>"GW"},
  {:name =>"Guyana", :iso_code => 328 , :iso_alpha3 =>"GUY", :iso_alpha2 =>"GY"},
  {:name =>"Haití", :iso_code => 332 , :iso_alpha3 =>"HTI", :iso_alpha2 =>"HT"},
  {:name =>"Islas Heard y McDonald", :iso_code => 334 , :iso_alpha3 =>"HMD", :iso_alpha2 =>"HM"},
  {:name =>"Honduras", :iso_code => 340 , :iso_alpha3 =>"HND", :iso_alpha2 =>"HN"},
  {:name =>"Hong Kong", :iso_code => 344 , :iso_alpha3 =>"HKG", :iso_alpha2 =>"HK"},
  {:name =>"Hungría", :iso_code => 348 , :iso_alpha3 =>"HUN", :iso_alpha2 =>"HU"},
  {:name =>"India", :iso_code => 356 , :iso_alpha3 =>"IND", :iso_alpha2 =>"IN"},
  {:name =>"Indonesia", :iso_code => 360 , :iso_alpha3 =>"IDN", :iso_alpha2 =>"ID"},
  {:name =>"Irán", :iso_code => 364 , :iso_alpha3 =>"IRN", :iso_alpha2 =>"IR"},
  {:name =>"Irak", :iso_code => 368 , :iso_alpha3 =>"IRQ", :iso_alpha2 =>"IQ"},
  {:name =>"Irlanda", :iso_code => 372 , :iso_alpha3 =>"IRL", :iso_alpha2 =>"IE"},
  {:name =>"Islandia", :iso_code => 352 , :iso_alpha3 =>"ISL", :iso_alpha2 =>"IS"},
  {:name =>"Israel", :iso_code => 376 , :iso_alpha3 =>"ISR", :iso_alpha2 =>"IL"},
  {:name =>"Italia", :iso_code => 380 , :iso_alpha3 =>"ITA", :iso_alpha2 =>"IT"},
  {:name =>"Jamaica", :iso_code => 388 , :iso_alpha3 =>"JAM", :iso_alpha2 =>"JM"},
  {:name =>"Japón", :iso_code => 392 , :iso_alpha3 =>"JPN", :iso_alpha2 =>"JP"},
  {:name =>"Jersey", :iso_code => 832 , :iso_alpha3 =>"JEY", :iso_alpha2 =>"JE"},
  {:name =>"Jordania", :iso_code => 400 , :iso_alpha3 =>"JOR", :iso_alpha2 =>"JO"},
  {:name =>"Kazajistán", :iso_code => 398 , :iso_alpha3 =>"KAZ", :iso_alpha2 =>"KZ"},
  {:name =>"Kenia", :iso_code => 404 , :iso_alpha3 =>"KEN", :iso_alpha2 =>"KE"},
  {:name =>"Kirguistán", :iso_code => 417 , :iso_alpha3 =>"KGZ", :iso_alpha2 =>"KG"},
  {:name =>"Kiribati", :iso_code => 296 , :iso_alpha3 =>"KIR", :iso_alpha2 =>"KI"},
  {:name =>"Kuwait", :iso_code => 414 , :iso_alpha3 =>"KWT", :iso_alpha2 =>"KW"},
  {:name =>"Laos", :iso_code => 418 , :iso_alpha3 =>"LAO", :iso_alpha2 =>"LA"},
  {:name =>"Lesoto", :iso_code => 426 , :iso_alpha3 =>"LSO", :iso_alpha2 =>"LS"},
  {:name =>"Letonia", :iso_code => 428 , :iso_alpha3 =>"LVA", :iso_alpha2 =>"LV"},
  {:name =>"Líbano", :iso_code => 422 , :iso_alpha3 =>"LBN", :iso_alpha2 =>"LB"},
  {:name =>"Liberia", :iso_code => 430 , :iso_alpha3 =>"LBR", :iso_alpha2 =>"LR"},
  {:name =>"Libia", :iso_code => 434 , :iso_alpha3 =>"LBY", :iso_alpha2 =>"LY"},
  {:name =>"Liechtenstein", :iso_code => 438 , :iso_alpha3 =>"LIE", :iso_alpha2 =>"LI"},
  {:name =>"Lituania", :iso_code => 440 , :iso_alpha3 =>"LTU", :iso_alpha2 =>"LT"},
  {:name =>"Luxemburgo", :iso_code => 442 , :iso_alpha3 =>"LUX", :iso_alpha2 =>"LU"},
  {:name =>"Macao", :iso_code => 446 , :iso_alpha3 =>"MAC", :iso_alpha2 =>"MO"},
  {:name =>"República de Macedonia", :iso_code => 807 , :iso_alpha3 =>"MKD", :iso_alpha2 =>"MK"},
  {:name =>"Madagascar", :iso_code => 450 , :iso_alpha3 =>"MDG", :iso_alpha2 =>"MG"},
  {:name =>"Malasia", :iso_code => 458 , :iso_alpha3 =>"MYS", :iso_alpha2 =>"MY"},
  {:name =>"Malaui", :iso_code => 454 , :iso_alpha3 =>"MWI", :iso_alpha2 =>"MW"},
  {:name =>"Maldivas", :iso_code => 462 , :iso_alpha3 =>"MDV", :iso_alpha2 =>"MV"},
  {:name =>"Malí", :iso_code => 466 , :iso_alpha3 =>"MLI", :iso_alpha2 =>"ML"},
  {:name =>"Malta", :iso_code => 470 , :iso_alpha3 =>"MLT", :iso_alpha2 =>"MT"},
  {:name =>"Islas Malvinas", :iso_code => 238 , :iso_alpha3 =>"FLK", :iso_alpha2 =>"FK"},
  {:name =>"Isla de Man", :iso_code => 833 , :iso_alpha3 =>"IMN", :iso_alpha2 =>"IM"},
  {:name =>"Islas Marianas del Norte", :iso_code => 580 , :iso_alpha3 =>"MNP", :iso_alpha2 =>"MP"},
  {:name =>"Marruecos", :iso_code => 504 , :iso_alpha3 =>"MAR", :iso_alpha2 =>"MA"},
  {:name =>"Islas Marshall", :iso_code => 584 , :iso_alpha3 =>"MHL", :iso_alpha2 =>"MH"},
  {:name =>"Martinica", :iso_code => 474 , :iso_alpha3 =>"MTQ", :iso_alpha2 =>"MQ"},
  {:name =>"Mauricio", :iso_code => 480 , :iso_alpha3 =>"MUS", :iso_alpha2 =>"MU"},
  {:name =>"Mauritania", :iso_code => 478 , :iso_alpha3 =>"MRT", :iso_alpha2 =>"MR"},
  {:name =>"Mayotte", :iso_code => 175 , :iso_alpha3 =>"MYT", :iso_alpha2 =>"YT"},
  {:name =>"México", :iso_code => 484 , :iso_alpha3 =>"MEX", :iso_alpha2 =>"MX"},
  {:name =>"Micronesia", :iso_code => 583 , :iso_alpha3 =>"FSM", :iso_alpha2 =>"FM"},
  {:name =>"Moldavia", :iso_code => 498 , :iso_alpha3 =>"MDA", :iso_alpha2 =>"MD"},
  {:name =>"Mónaco", :iso_code => 492 , :iso_alpha3 =>"MCO", :iso_alpha2 =>"MC"},
  {:name =>"Mongolia", :iso_code => 496 , :iso_alpha3 =>"MNG", :iso_alpha2 =>"MN"},
  {:name =>"Montenegro", :iso_code => 499 , :iso_alpha3 =>"MNE", :iso_alpha2 =>"ME"},
  {:name =>"Montserrat", :iso_code => 500 , :iso_alpha3 =>"MSR", :iso_alpha2 =>"MS"},
  {:name =>"Mozambique", :iso_code => 508 , :iso_alpha3 =>"MOZ", :iso_alpha2 =>"MZ"},
  {:name =>"Namibia", :iso_code => 516 , :iso_alpha3 =>"NAM", :iso_alpha2 =>"NA"},
  {:name =>"Nauru", :iso_code => 520 , :iso_alpha3 =>"NRU", :iso_alpha2 =>"NR"},
  {:name =>"Isla de Navidad", :iso_code => 162 , :iso_alpha3 =>"CXR", :iso_alpha2 =>"CX"},
  {:name =>"Nepal", :iso_code => 524 , :iso_alpha3 =>"NPL", :iso_alpha2 =>"NP"},
  {:name =>"Nicaragua", :iso_code => 558 , :iso_alpha3 =>"NIC", :iso_alpha2 =>"NI"},
  {:name =>"Níger", :iso_code => 562 , :iso_alpha3 =>"NER", :iso_alpha2 =>"NE"},
  {:name =>"Nigeria", :iso_code => 566 , :iso_alpha3 =>"NGA", :iso_alpha2 =>"NG"},
  {:name =>"Niue", :iso_code => 570 , :iso_alpha3 =>"NIU", :iso_alpha2 =>"NU"},
  {:name =>"Norfolk", :iso_code => 574 , :iso_alpha3 =>"NFK", :iso_alpha2 =>"NF"},
  {:name =>"Noruega", :iso_code => 578 , :iso_alpha3 =>"NOR", :iso_alpha2 =>"NO"},
  {:name =>"Nueva Caledonia", :iso_code => 540 , :iso_alpha3 =>"NCL", :iso_alpha2 =>"NC"},
  {:name =>"Nueva Zelanda", :iso_code => 554 , :iso_alpha3 =>"NZL", :iso_alpha2 =>"NZ"},
  {:name =>"Omán", :iso_code => 512 , :iso_alpha3 =>"OMN", :iso_alpha2 =>"OM"},
  {:name =>"Países Bajos", :iso_code => 528 , :iso_alpha3 =>"NLD", :iso_alpha2 =>"NL"},
  {:name =>"Pakistán", :iso_code => 586 , :iso_alpha3 =>"PAK", :iso_alpha2 =>"PK"},
  {:name =>"Palaos", :iso_code => 585 , :iso_alpha3 =>"PLW", :iso_alpha2 =>"PW"},
  {:name =>"Autoridad Nacional Palestina", :iso_code => 275 , :iso_alpha3 =>"PSE", :iso_alpha2 =>"PS"},
  {:name =>"Panamá", :iso_code => 591 , :iso_alpha3 =>"PAN", :iso_alpha2 =>"PA"},
  {:name =>"Papúa Nueva Guinea", :iso_code => 598 , :iso_alpha3 =>"PNG", :iso_alpha2 =>"PG"},
  {:name =>"Paraguay", :iso_code => 600 , :iso_alpha3 =>"PRY", :iso_alpha2 =>"PY"},
  {:name =>"Perú", :iso_code => 604 , :iso_alpha3 =>"PER", :iso_alpha2 =>"PE"},
  {:name =>"Islas Pitcairn", :iso_code => 612 , :iso_alpha3 =>"PCN", :iso_alpha2 =>"PN"},
  {:name =>"Polinesia Francesa", :iso_code => 258 , :iso_alpha3 =>"PYF", :iso_alpha2 =>"PF"},
  {:name =>"Polonia", :iso_code => 616 , :iso_alpha3 =>"POL", :iso_alpha2 =>"PL"},
  {:name =>"Portugal", :iso_code => 620 , :iso_alpha3 =>"PRT", :iso_alpha2 =>"PT"},
  {:name =>"Puerto Rico", :iso_code => 630 , :iso_alpha3 =>"PRI", :iso_alpha2 =>"PR"},
  {:name =>"Catar", :iso_code => 634 , :iso_alpha3 =>"QAT", :iso_alpha2 =>"QA"},
  {:name =>"Inglaterra", :iso_code => 826 , :iso_alpha3 =>"GBR", :iso_alpha2 =>"GB"},
  {:name =>"Reunión", :iso_code => 638 , :iso_alpha3 =>"REU", :iso_alpha2 =>"RE"},
  {:name =>"Ruanda", :iso_code => 646 , :iso_alpha3 =>"RWA", :iso_alpha2 =>"RW"},
  {:name =>"Rumania", :iso_code => 642 , :iso_alpha3 =>"ROU", :iso_alpha2 =>"RO"},
  {:name =>"Rusia", :iso_code => 643 , :iso_alpha3 =>"RUS", :iso_alpha2 =>"RU"},
  {:name =>"República Árabe Saharaui Democrática", :iso_code => 732 , :iso_alpha3 =>"ESH", :iso_alpha2 =>"EH"},
  {:name =>"Islas Salomón", :iso_code => 90 , :iso_alpha3 =>"SLB", :iso_alpha2 =>"SB"},
  {:name =>"Samoa", :iso_code => 882 , :iso_alpha3 =>"WSM", :iso_alpha2 =>"WS"},
  {:name =>"Samoa Americana", :iso_code => 16 , :iso_alpha3 =>"ASM", :iso_alpha2 =>"AS"},
  {:name =>"San Bartolomé", :iso_code => 652 , :iso_alpha3 =>"BLM", :iso_alpha2 =>"BL"},
  {:name =>"San Cristóbal y Nieves", :iso_code => 659 , :iso_alpha3 =>"KNA", :iso_alpha2 =>"KN"},
  {:name =>"San Marino", :iso_code => 674 , :iso_alpha3 =>"SMR", :iso_alpha2 =>"SM"},
  {:name =>"San Martín", :iso_code => 663 , :iso_alpha3 =>"MAF", :iso_alpha2 =>"MF"},
  {:name =>"San Pedro y Miquelón", :iso_code => 666 , :iso_alpha3 =>"SPM", :iso_alpha2 =>"PM"},
  {:name =>"San Vicente y las Granadinas", :iso_code => 670 , :iso_alpha3 =>"VCT", :iso_alpha2 =>"VC"},
  {:name =>"Santa Helena, A. y T.", :iso_code => 654 , :iso_alpha3 =>"SHN", :iso_alpha2 =>"SH"},
  {:name =>"Santa Lucía", :iso_code => 662 , :iso_alpha3 =>"LCA", :iso_alpha2 =>"LC"},
  {:name =>"Santo Tomé y Príncipe", :iso_code => 678 , :iso_alpha3 =>"STP", :iso_alpha2 =>"ST"},
  {:name =>"Senegal", :iso_code => 686 , :iso_alpha3 =>"SEN", :iso_alpha2 =>"SN"},
  {:name =>"Serbia", :iso_code => 688 , :iso_alpha3 =>"SRB", :iso_alpha2 =>"RS"},
  {:name =>"Seychelles", :iso_code => 690 , :iso_alpha3 =>"SYC", :iso_alpha2 =>"SC"},
  {:name =>"Sierra Leona", :iso_code => 694 , :iso_alpha3 =>"SLE", :iso_alpha2 =>"SL"},
  {:name =>"Singapur", :iso_code => 702 , :iso_alpha3 =>"SGP", :iso_alpha2 =>"SG"},
  {:name =>"Siria", :iso_code => 760 , :iso_alpha3 =>"SYR", :iso_alpha2 =>"SY"},
  {:name =>"Somalia", :iso_code => 706 , :iso_alpha3 =>"SOM", :iso_alpha2 =>"SO"},
  {:name =>"Sri Lanka", :iso_code => 144 , :iso_alpha3 =>"LKA", :iso_alpha2 =>"LK"},
  {:name =>"Suazilandia", :iso_code => 748 , :iso_alpha3 =>"SWZ", :iso_alpha2 =>"SZ"},
  {:name =>"Sudáfrica", :iso_code => 710 , :iso_alpha3 =>"ZAF", :iso_alpha2 =>"ZA"},
  {:name =>"Sudán", :iso_code => 729 , :iso_alpha3 =>"SDN", :iso_alpha2 =>"SD"},
  {:name =>"Sudán del Sur", :iso_code => 728 , :iso_alpha3 =>"SSD", :iso_alpha2 =>"SS"},
  {:name =>"Suecia", :iso_code => 752 , :iso_alpha3 =>"SWE", :iso_alpha2 =>"SE"},
  {:name =>"Suiza", :iso_code => 756 , :iso_alpha3 =>"CHE", :iso_alpha2 =>"CH"},
  {:name =>"Surinam", :iso_code => 740 , :iso_alpha3 =>"SUR", :iso_alpha2 =>"SR"},
  {:name =>"Svalbard y Jan Mayen", :iso_code => 744 , :iso_alpha3 =>"SJM", :iso_alpha2 =>"SJ"},
  {:name =>"Tailandia", :iso_code => 764 , :iso_alpha3 =>"THA", :iso_alpha2 =>"TH"},
  {:name =>"Taiwán", :iso_code => 158 , :iso_alpha3 =>"TWN", :iso_alpha2 =>"TW"},
  {:name =>"Tanzania", :iso_code => 834 , :iso_alpha3 =>"TZA", :iso_alpha2 =>"TZ"},
  {:name =>"Tayikistán", :iso_code => 762 , :iso_alpha3 =>"TJK", :iso_alpha2 =>"TJ"},
  {:name =>"Territorio Británico del Océano Índico", :iso_code => 86 , :iso_alpha3 =>"IOT", :iso_alpha2 =>"IO"},
  {:name =>"Territorios Australes Franceses", :iso_code => 260 , :iso_alpha3 =>"ATF", :iso_alpha2 =>"TF"},
  {:name =>"Timor Oriental", :iso_code => 626 , :iso_alpha3 =>"TLS", :iso_alpha2 =>"TL"},
  {:name =>"Togo", :iso_code => 768 , :iso_alpha3 =>"TGO", :iso_alpha2 =>"TG"},
  {:name =>"Tokelau", :iso_code => 772 , :iso_alpha3 =>"TKL", :iso_alpha2 =>"TK"},
  {:name =>"Tonga", :iso_code => 776 , :iso_alpha3 =>"TON", :iso_alpha2 =>"TO"},
  {:name =>"Trinidad y Tobago", :iso_code => 780 , :iso_alpha3 =>"TTO", :iso_alpha2 =>"TT"},
  {:name =>"Túnez", :iso_code => 788 , :iso_alpha3 =>"TUN", :iso_alpha2 =>"TN"},
  {:name =>"Islas Turcas y Caicos", :iso_code => 796 , :iso_alpha3 =>"TCA", :iso_alpha2 =>"TC"},
  {:name =>"Turkmenistán", :iso_code => 795 , :iso_alpha3 =>"TKM", :iso_alpha2 =>"TM"},
  {:name =>"Turquía", :iso_code => 792 , :iso_alpha3 =>"TUR", :iso_alpha2 =>"TR"},
  {:name =>"Tuvalu", :iso_code => 798 , :iso_alpha3 =>"TUV", :iso_alpha2 =>"TV"},
  {:name =>"Ucrania", :iso_code => 804 , :iso_alpha3 =>"UKR", :iso_alpha2 =>"UA"},
  {:name =>"Uganda", :iso_code => 800 , :iso_alpha3 =>"UGA", :iso_alpha2 =>"UG"},
  {:name =>"Uruguay", :iso_code => 858 , :iso_alpha3 =>"URY", :iso_alpha2 =>"UY"},
  {:name =>"Uzbekistán", :iso_code => 860 , :iso_alpha3 =>"UZB", :iso_alpha2 =>"UZ"},
  {:name =>"Vanuatu", :iso_code => 548 , :iso_alpha3 =>"VUT", :iso_alpha2 =>"VU"},
  {:name =>"Ciudad del Vaticano", :iso_code => 336 , :iso_alpha3 =>"VAT", :iso_alpha2 =>"VA"},
  {:name =>"Venezuela", :iso_code => 862 , :iso_alpha3 =>"VEN", :iso_alpha2 =>"VE"},
  {:name =>"Vietnam", :iso_code => 704 , :iso_alpha3 =>"VNM", :iso_alpha2 =>"VN"},
  {:name =>"Islas Vírgenes Británicas", :iso_code => 92 , :iso_alpha3 =>"VGB", :iso_alpha2 =>"VG"},
  {:name =>"Islas Vírgenes de los Estados Unidos", :iso_code => 850 , :iso_alpha3 =>"VIR", :iso_alpha2 =>"VI"},
  {:name =>"Wallis y Futuna", :iso_code => 876 , :iso_alpha3 =>"WLF", :iso_alpha2 =>"WF"},
  {:name =>"Yemen", :iso_code => 887 , :iso_alpha3 =>"YEM", :iso_alpha2 =>"YE"},
  {:name =>"Yibuti", :iso_code => 262 , :iso_alpha3 =>"DJI", :iso_alpha2 =>"DJ"},
  {:name =>"Zambia", :iso_code => 894 , :iso_alpha3 =>"ZMB", :iso_alpha2 =>"ZM"},
  {:name =>"Zimbabue", :iso_code => 716 , :iso_alpha3 =>"ZWE", :iso_alpha2 =>"ZW"},
  {:name => "Gales", :iso_code => 1826, :iso_alpha3 => "GB-WLS", :iso_alpha2 => "GB-WLS" }])

  Location.create([
    { name: "Doha" , country_id: 180 },
    { name: "Jor" , country_id: 180 },
    { name: "Rayán" , country_id: 180 },
    { name: "Lusail" , country_id: 180 },
    { name: "Al Wakrah" , country_id: 180 }
  ])

  Stadium.create([
    { name: "Estadio Al Thumama", location_id: 1 },
    { name: "Estadio Al Bayt", location_id: 2 },
    { name: "Estadio Internacional Khalifa", location_id: 3 },
    { name: "Estadio Ahmed bin Ali", location_id: 3  },
    { name: "Estadio Icónico", location_id: 4 },
    { name: "Estadio Ciudad de la Educación", location_id: 1 },
    { name: "Estadio 974", location_id: 3 },
    { name: "Estadio Al Janoub", location_id: 5 }
  ])

  Match.create([
    { name: "002", competing_team_1_id: 3, competing_team_2_id: 4, stadium_id: 1, date_time: "2021-11-21T10:00:00+00:00" },
    { name: "001", competing_team_1_id: 1, competing_team_2_id: 2, stadium_id: 2, date_time: "2021-11-21T16:00:00+00:00" },
    { name: "018", competing_team_1_id: 1, competing_team_2_id: 3, stadium_id: 1, date_time: "2021-11-25T13:00:00+00:00" },
    { name: "019", competing_team_1_id: 4, competing_team_2_id: 2, stadium_id: 3, date_time: "2021-11-25T16:00:00+00:00" },
    { name: "035", competing_team_1_id: 2, competing_team_2_id: 3, stadium_id: 3, date_time: "2021-11-29T15:00:00+00:00" },
    { name: "036", competing_team_1_id: 4, competing_team_2_id: 1, stadium_id: 2, date_time: "2021-11-29T15:00:00+00:00" },
    { name: "003", competing_team_1_id: 5, competing_team_2_id: 6, stadium_id: 3, date_time: "2021-11-21T13:00:00+00:00" },
    { name: "004", competing_team_1_id: 7, competing_team_2_id: 8, stadium_id: 4, date_time: "2021-11-21T19:00:00+00:00" },
    { name: "017", competing_team_1_id: 8, competing_team_2_id: 6, stadium_id: 4, date_time: "2021-11-25T10:00:00+00:00" },
    { name: "020", competing_team_1_id: 5, competing_team_2_id: 7, stadium_id: 2, date_time: "2021-11-25T19:00:00+00:00" },
    { name: "033", competing_team_1_id: 8, competing_team_2_id: 5, stadium_id: 4, date_time: "2021-11-29T19:00:00+00:00" },
    { name: "034", competing_team_1_id: 6, competing_team_2_id: 7, stadium_id: 1, date_time: "2021-11-29T19:00:00+00:00" },
    { name: "008", competing_team_1_id: 9, competing_team_2_id: 10, stadium_id: 5, date_time: "2021-11-21T10:00:00+00:00" },
    { name: "007", competing_team_1_id: 11, competing_team_2_id: 12, stadium_id: 7, date_time: "2021-11-21T16:00:00+00:00" },
    { name: "022", competing_team_1_id: 12, competing_team_2_id: 10, stadium_id: 6, date_time: "2021-11-26T13:00:00+00:00" },
    { name: "024", competing_team_1_id: 9, competing_team_2_id: 11, stadium_id: 5, date_time: "2021-11-26T19:00:00+00:00" },
    { name: "039", competing_team_1_id: 12, competing_team_2_id: 9, stadium_id: 7, date_time: "2021-11-30T19:00:00+00:00" },
    { name: "040", competing_team_1_id: 10, competing_team_2_id: 11, stadium_id: 5, date_time: "2021-11-30T19:00:00+00:00" },
    { name: "006", competing_team_1_id: 15, competing_team_2_id: 16, stadium_id: 6, date_time: "2021-11-22T13:00:00+00:00" },
    { name: "005", competing_team_1_id: 13, competing_team_2_id: 14, stadium_id: 8, date_time: "2021-11-22T19:00:00+00:00" },
    { name: "021", competing_team_1_id: 16, competing_team_2_id: 14, stadium_id: 8, date_time: "2021-11-26T10:00:00+00:00" },
    { name: "023", competing_team_1_id: 13, competing_team_2_id: 15, stadium_id: 7, date_time: "2021-11-26T16:00:00+00:00" },
    { name: "037", competing_team_1_id: 14, competing_team_2_id: 15, stadium_id: 8, date_time: "2021-11-30T15:00:00+00:00" },
    { name: "038", competing_team_1_id: 16, competing_team_2_id: 13, stadium_id: 6, date_time: "2021-11-30T15:00:00+00:00" },
    { name: "011", competing_team_1_id: 19, competing_team_2_id: 20, stadium_id: 3, date_time: "2021-11-23T13:00:00+00:00" },
    { name: "010", competing_team_1_id: 17, competing_team_2_id: 18, stadium_id: 1, date_time: "2021-11-23T16:00:00+00:00" },
    { name: "025", competing_team_1_id: 20, competing_team_2_id: 18, stadium_id: 4, date_time: "2021-11-27T10:00:00+00:00" },
    { name: "028", competing_team_1_id: 17, competing_team_2_id: 19, stadium_id: 2, date_time: "2021-11-27T19:00:00+00:00" },
    { name: "043", competing_team_1_id: 20, competing_team_2_id: 17, stadium_id: 3, date_time: "2021-12-01T19:00:00+00:00" },
    { name: "044", competing_team_1_id: 18, competing_team_2_id: 19, stadium_id: 2, date_time: "2021-12-01T19:00:00+00:00" },
    { name: "012", competing_team_1_id: 23, competing_team_2_id: 24, stadium_id: 2, date_time: "2021-11-23T10:00:00+00:00" },
    { name: "009", competing_team_1_id: 21, competing_team_2_id: 22, stadium_id: 4, date_time: "2021-11-23T19:00:00+00:00" },
    { name: "026", competing_team_1_id: 21, competing_team_2_id: 23, stadium_id: 1, date_time: "2021-11-27T13:00:00+00:00" },
    { name: "027", competing_team_1_id: 24, competing_team_2_id: 22, stadium_id: 3, date_time: "2021-11-27T16:00:00+00:00" },
    { name: "041", competing_team_1_id: 24, competing_team_2_id: 21, stadium_id: 4, date_time: "2021-12-01T15:00:00+00:00" },
    { name: "042", competing_team_1_id: 22, competing_team_2_id: 23, stadium_id: 1, date_time: "2021-12-01T15:00:00+00:00" },
    { name: "013", competing_team_1_id: 27, competing_team_2_id: 28, stadium_id: 8, date_time: "2021-11-24T10:00:00+00:00" },
    { name: "016", competing_team_1_id: 25, competing_team_2_id: 26, stadium_id: 5, date_time: "2021-11-24T19:00:00+00:00" },
    { name: "029", competing_team_1_id: 28, competing_team_2_id: 26, stadium_id: 8, date_time: "2021-11-28T10:00:00+00:00" },
    { name: "031", competing_team_1_id: 25, competing_team_2_id: 27, stadium_id: 7, date_time: "2021-11-28T16:00:00+00:00" },
    { name: "047", competing_team_1_id: 26, competing_team_2_id: 27, stadium_id: 7, date_time: "2021-12-02T19:00:00+00:00" },
    { name: "048", competing_team_1_id: 28, competing_team_2_id: 25, stadium_id: 5, date_time: "2021-12-02T19:00:00+00:00" },
    { name: "014", competing_team_1_id: 31, competing_team_2_id: 32, stadium_id: 6, date_time: "2021-11-24T13:00:00+00:00" },
    { name: "015", competing_team_1_id: 29, competing_team_2_id: 30, stadium_id: 7, date_time: "2021-11-24T16:00:00+00:00" },
    { name: "030", competing_team_1_id: 32, competing_team_2_id: 30, stadium_id: 6, date_time: "2021-11-28T13:00:00+00:00" },
    { name: "032", competing_team_1_id: 29, competing_team_2_id: 31, stadium_id: 5, date_time: "2021-11-28T19:00:00+00:00" },
    { name: "045", competing_team_1_id: 30, competing_team_2_id: 31, stadium_id: 8, date_time: "2021-12-02T15:00:00+00:00" },
    { name: "046", competing_team_1_id: 32, competing_team_2_id: 29, stadium_id: 6, date_time: "2021-12-02T15:00:00+00:00" }])
